# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9c9dd1d4bd4eca5603fde14e5903c8af3bce43228ded2a84911e2e4211b44666dc3ccd89f377e5d42346badd2518821c9e473f075024436de6fb82eb6a98b166

test:
  secret_key_base: a08aec031d6d9a9142e69423c0b3f9a370f84678889bd9b015a48791c11f4f611041b58ad436a6b315b0a8b9eb0d400e098a0319f1ecd38afcc7a6928778567e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
